name: "Build and Deploy to ECR"
description: "Builds an image from a dockerfile, and pushes it up to ECR"
inputs:
  deploy:
    description: "Whether to push the image to ECR after building it"
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    -run: |
      BRANCH=$(echo ${{github.ref}} | cut -f3 -d'/')
      CONTAINER_IMAGE="${{secrets.ECR_URI}}/github/${{github.repository}}/${BRANCH}"
      CONTAINER_IMAGE_SHA="${CONTAINER_IMAGE}:${{github.sha}}"
      CONTAINER_IMAGE_LATEST="${CONTAINER_IMAGE}:latest"
      AWS_REGION=$(echo ${{secrets.ECR_URI}} | cut -f4 -d'.')
      AWS_ACCESS_KEY_ID="${{secrets.ECR_AWS_ACCESS_KEY_ID}}" \
      AWS_SECRET_ACCESS_KEY="${{secrets.ECR_AWS_SECRET_ACCESS_KEY}}" \
        aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin ${{secrets.ECR_URI}}
      docker build -t $CONTAINER_IMAGE_SHA -t $CONTAINER_IMAGE_LATEST .
      [ "$INPUT_DEPLOY" = "true" ] \
        && docker push $CONTAINER_IMAGE_SHA \
        && docker push $CONTAINER_IMAGE_LATEST
     shell: bash