name: Build and Deploy to ECR
description: Builds an image from a dockerfile, and pushes it up to ECR
inputs:
  deploy:
    description: Whether to push the image to ECR after building it
    required: false
    default: 'true'
  ecr_uri:
    description: The URI for the ECR repository
    required: true
  access_key_id:
    description: An AWS Access Key ID
    required: true
  secret_access_key:
    description: An AWS Secret Access Key
    required: true
runs:
  using: composite
  steps:
    - name: Setup Environment
      id: setup
      run: |
        echo ::set-env name=CONTAINER_NAME::${{ inputs.ecr_uri }}/github/$GITHUB_REPOSITORY/$(cut --delimiter '/' --fields 3- <<< "$GITHUB_REF")
        echo ::set-output name=region::$(cut --delimiter '.' --fields 4 <<< ${{ inputs.ecr_uri }})
      shell: bash
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.access_key_id }}
        aws-secret-access-key: ${{ secrets.secret_access_key }}
        aws-region: ${{ steps.setup.outputs.region }}
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build and tag image
      run: docker build --tag $CONTAINER_NAME:$GITHUB_SHA --tag $CONTAINER_NAME:latest .
    - name: Push tags to ECR
      if: ${{ inputs.deploy == 'true' }}
      run: |
        docker push $CONTAINER_NAME:$GITHUB_SHA
        docker push $CONTAINER_NAME:latest
