name: "Build and Deploy to ECR"
description: "Builds an image from a dockerfile, and pushes it up to ECR"
inputs:
  deploy:
    description: "Whether to push the image to ECR after building it"
    required: false
    default: 'true'
  ecr_uri:
    description: "The URI for the ECR repository"
    required: true
  access_key_id:
    description: "An AWS Access Key ID"
    required: true
  secret_access_key:
    description: "An AWS Secret Access Key"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        BRANCH=$(echo ${{github.ref}} | cut -f3 -d'/')
        CONTAINER_IMAGE="${{inputs.ecr_uri}}/github/${{github.repository}}/${BRANCH}"
        CONTAINER_IMAGE_SHA="${CONTAINER_IMAGE}:${{github.sha}}"
        CONTAINER_IMAGE_LATEST="${CONTAINER_IMAGE}:latest"
        AWS_REGION=$(echo "${{inputs.ecr_uri}}" | cut -f4 -d'.')
        AWS_ACCESS_KEY_ID="${{inputs.access_key_id}}" \
        AWS_SECRET_ACCESS_KEY="${{inputs.secret_access_key}}" \
          aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin ${{inputs.ecr_uri}}
        docker build -t $CONTAINER_IMAGE_SHA -t $CONTAINER_IMAGE_LATEST .
        [ "${{inputs.deploy}}" = "true" ] \
          && docker push $CONTAINER_IMAGE_SHA \
          && docker push $CONTAINER_IMAGE_LATEST
      shell: bash
